version: '3.9'
services:
    IS-Postgres:
      image: postgres:latest
      volumes:
        - is-postgres-db-data:/var/lib/postgresql/isdata
      ports:
        - 5433:5432
      environment:
        POSTGRES_PASSWORD_FILE: /run/secrets/is_db_password
        POSTGRES_USER: user
        POSTGRES_DB: IS-Postgres
      secrets:
        - is_db_password
    IS-User-Postgres:
      image: postgres:latest
      volumes:
        - is-user-postgres-db-data:/var/lib/postgresql/isuserdata
      ports:
        - 5434:5432
      environment:
        POSTGRES_PASSWORD_FILE: /run/secrets/is_user_db_password
        POSTGRES_USER: user
        POSTGRES_DB: IS-User-Postgres
      secrets:
        - is_user_db_password
    TheGym-Postgres:
      image: postgres:latest
      volumes:
        - postgres-db-data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD_FILE: /run/secrets/thegym_db_password
        POSTGRES_USER_FILE: /run/secrets/thegym_db_user
        POSTGRES_DB: TheGym-Postgres
      secrets:
        - thegym_db_password
        - thegym_db_user
secrets:
  is_db_password:
    file: ./Secrets/is_db_password.txt
  thegym_db_password:
    file: ./Secrets/thegym_db_password.txt
  thegym_db_user:
    file: ./Secrets/thegym_db_user.txt
  is_user_db_password:
    file: ./Secrets/is_user_db_password.txt
volumes:
  is-postgres-db-data:
  is-user-postgres-db-data:
  postgres-db-data:
